# Generated by Django 5.0.3 on 2024-04-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_id_alter_order_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
