# Generated by Django 5.0.3 on 2024-04-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_delivery_address_order_delivery_addrss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_addrss',
            new_name='delivery_address',
        ),
    ]
