# Generated by Django 5.0.3 on 2024-04-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_order_city_order_state_order_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons_requested', models.FloatField()),
                ('state', models.CharField(max_length=100)),
                ('has_history', models.BooleanField()),
                ('suggested_price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
