# Generated by Django 5.0.3 on 2024-04-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_fuelquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelquote',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='fuelquote',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='fuelquote',
            name='zip_code',
            field=models.CharField(default='00000', max_length=20),
        ),
    ]
