# Generated by Django 5.0.3 on 2024-04-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_fuelquote_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="fuelquote", name="user",),
    ]
