# Generated by Django 5.0.3 on 2024-04-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_remove_fuelquote_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gallons_requested",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="has_history",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="suggested_price",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="order", name="total_amount", field=models.FloatField(null=True),
        ),
    ]
