# Generated by Django 5.0.3 on 2024-04-27 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_order_gallons_requested_order_has_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelquote",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.customer",
            ),
        ),
    ]
